export const portfolioCopy = {
    pt: {
        discipline: "Design & desenvolvimento independente", availability: "Disponível para novos projetos",
        heroLines: ["Sua ideia.", "Com impacto."], heroVariants: ["Com impacto.", "Com presença.", "Sem limites."],
        loading: "Preparando a experiência", loaderLabel: "PORTFÓLIO — 2026", loaderWords: "IMAGINAR · CONSTRUIR · TRANSFORMAR", loaderNote: "UMA IDEIA. INFINITAS POSSIBILIDADES.",
        logoHint: "Segure para revelar o que há por trás", logoAction: "Mantenha o mouse, o toque ou Espaço pressionado para carregar e abrir a armadura do AL. Continue até oito segundos para ascender as placas e transformar o núcleo arcano. Solte a qualquer momento para recompor.", logoRelease: "Núcleo revelado · continue segurando", logoCaption: "DESIGN + CÓDIGO + POSSIBILIDADES",
        logoAscending: "Liberando as placas · mantenha pressionado", logoInfusing: "Infundindo energia arcana", logoArcane: "AL arcano · solte para recompor",
        logoCharging: "Carregando energia · mantenha pressionado", logoUnlocking: "Destravando a armadura", logoOpening: "Revelando o núcleo", logoReturning: "Recompondo o AL",
        heroDescription: "Sites que fazem sua marca ser lembrada. Sistemas que tornam sua empresa mais simples. Do primeiro conceito ao último detalhe, eu construo para o seu negócio ir além.",
        heroNote: "Design com intenção. Código que resolve.", start: "Vamos criar seu projeto", viewWork: "Explore os projetos", scroll: "Role para descobrir",
        selected: "Trabalho selecionado", workTitle: "Ideias que viraram realidade.", workDescription: "Negócios diferentes. Soluções feitas para cada um. Conheça alguns projetos que já saíram do papel.",
        all: "Todos", websites: "Sites", systems: "Sistemas", previous: "Projeto anterior", next: "Próximo projeto", visit: "Abrir projeto", scrollWork: "Continue rolando para explorar", workCount: "projetos selecionados",
        solutions: "O que construo", servicesTitle: "Bonito é só o começo.", servicesDescription: "Uma presença digital precisa trabalhar por você. Da primeira impressão à operação do dia a dia, cada solução tem um propósito.",
        serviceResults: ["Sua marca, com credibilidade.", "Do interesse à conversa.", "Menos tarefas. Mais controle.", "Código melhor. Equipe mais forte."],
        statement: "Seu próximo site pode ser a melhor primeira impressão do seu negócio. Seu próximo sistema, a mudança que faltava na sua rotina.",
        aboutLabel: "Quem vai construir com você", aboutTitle: "Prazer, Alex.", aboutIntro: "Eu conecto o que seu negócio precisa ao que a tecnologia pode fazer.",
        aboutBody: "Sou desenvolvedor Full Stack e fundador da TKZ Dev. Trabalho de perto com cada cliente para transformar ideias em sites e sistemas com identidade, desempenho e uma experiência que faz sentido para quem usa.",
        aboutExtra: "Você fala diretamente com quem cria. Da estratégia ao lançamento, eu cuido do design, do código e dos detalhes que fazem o projeto funcionar no mundo real.",
        experience: "Minha trajetória", processLabel: "Da conversa ao lançamento", processTitle: "Um processo claro. Um projeto seu.",
        feedbackLabel: "Quem já confiou", feedbackTitle: "Projetos entregues. Relações construídas.",
        stackLabel: "Por trás de cada entrega", stackTitle: "Criatividade na frente. Tecnologia na base.",
        contactLabel: "O próximo projeto pode ser o seu", contactLines: ["Vamos tirar", "do papel?"], contactDescription: "Me conte sobre seu negócio e o que você quer construir. A primeira conversa é o começo de uma boa ideia.",
        whatsapp: "Conversar no WhatsApp", email: "Prefere e-mail?", backTop: "Voltar ao topo",
        navLabel: "Menu principal", openMenu: "Abrir menu", closeMenu: "Fechar menu", pause: "Pausar animações", resume: "Ativar animações", motion: "Movimento", motionOn: "Ligado", motionOff: "Pausado",
        footerNote: "Feito com intenção, do design ao código.", clientFocus: "Sites & sistemas sob medida", portraitAlt: "Alex Lima, desenvolvedor Full Stack",
        projectKinds: ["Plataforma de oportunidades", "E-commerce & catálogo", "Site institucional", "SaaS & gestão"],
    },
    en: {
        discipline: "Independent design & development", availability: "Available for new projects", heroLines: ["Your idea.", "With impact."], heroVariants: ["With impact.", "In motion.", "Without limits."],
        loading: "Preparing the experience", loaderLabel: "PORTFOLIO — 2026", loaderWords: "IMAGINE · BUILD · TRANSFORM", loaderNote: "ONE IDEA. ENDLESS POSSIBILITIES.",
        logoHint: "Hold to reveal what's underneath", logoAction: "Hold the mouse, touch or Space to charge and open the AL armor. Keep holding for eight seconds to lift the plates and transform the arcane core. Release at any time to reassemble.", logoRelease: "Core revealed · keep holding", logoCaption: "DESIGN + CODE + POSSIBILITIES",
        logoAscending: "Releasing the plates · keep holding", logoInfusing: "Infusing arcane energy", logoArcane: "Arcane AL · release to reassemble",
        logoCharging: "Charging energy · keep holding", logoUnlocking: "Unlocking the armor", logoOpening: "Revealing the core", logoReturning: "Reassembling AL",
        heroDescription: "Websites that make your brand memorable. Systems that make your business simpler. From the first concept to the final detail, I build to take your business further.",
        heroNote: "Intentional design. Code that delivers.", start: "Let's create your project", viewWork: "Explore the projects", scroll: "Scroll to discover",
        selected: "Selected work", workTitle: "Ideas turned into reality.", workDescription: "Different businesses. Solutions built for each one. Explore a selection of projects brought to life.",
        all: "All", websites: "Websites", systems: "Systems", previous: "Previous project", next: "Next project", visit: "Visit project", scrollWork: "Keep scrolling to explore", workCount: "selected projects",
        solutions: "What I build", servicesTitle: "Good looks are just the start.", servicesDescription: "Your digital presence should work for you. From the first impression to everyday operations, every solution has a purpose.",
        serviceResults: ["A credible brand presence.", "From interest to conversation.", "Less work. More control.", "Better code. Stronger teams."],
        statement: "Your next website can be your business's best first impression. Your next system, the change your daily work was missing.",
        aboutLabel: "Who's building with you", aboutTitle: "Hello, I'm Alex.", aboutIntro: "I connect what your business needs with what technology can do.",
        aboutBody: "I'm a Full Stack developer and founder of TKZ Dev. I work closely with each client to turn ideas into websites and systems with identity, performance and an experience that makes sense for the people using them.",
        aboutExtra: "You talk directly to the person creating your project. From strategy to launch, I take care of the design, code and details that make it work in the real world.",
        experience: "My journey", processLabel: "From conversation to launch", processTitle: "A clear process. A project that's yours.", feedbackLabel: "People who trusted me", feedbackTitle: "Projects delivered. Relationships built.",
        stackLabel: "Behind every delivery", stackTitle: "Creativity up front. Technology at the core.", contactLabel: "The next project could be yours", contactLines: ["Let's make", "it happen."],
        contactDescription: "Tell me about your business and what you'd like to build. The first conversation is where good ideas start.", whatsapp: "Talk on WhatsApp", email: "Prefer email?", backTop: "Back to top",
        navLabel: "Main navigation", openMenu: "Open menu", closeMenu: "Close menu", pause: "Pause animations", resume: "Enable animations", motion: "Motion", motionOn: "On", motionOff: "Paused",
        footerNote: "Built with intention, from design to code.", clientFocus: "Bespoke websites & systems", portraitAlt: "Alex Lima, Full Stack developer",
        projectKinds: ["Job opportunities platform", "E-commerce & catalog", "Business website", "SaaS & management"],
    },
    es: {
        discipline: "Diseño y desarrollo independiente", availability: "Disponible para nuevos proyectos", heroLines: ["Tu idea.", "Con impacto."], heroVariants: ["Con impacto.", "En movimiento.", "Sin límites."],
        loading: "Preparando la experiencia", loaderLabel: "PORTAFOLIO — 2026", loaderWords: "IMAGINAR · CONSTRUIR · TRANSFORMAR", loaderNote: "UNA IDEA. INFINITAS POSIBILIDADES.",
        logoHint: "Mantén para revelar lo que hay detrás", logoAction: "Mantén el ratón, el toque o Espacio para cargar y abrir la armadura del AL. Continúa durante ocho segundos para elevar las placas y transformar el núcleo arcano. Suelta en cualquier momento para recomponer.", logoRelease: "Núcleo revelado · sigue pulsando", logoCaption: "DISEÑO + CÓDIGO + POSIBILIDADES",
        logoAscending: "Liberando las placas · mantén pulsado", logoInfusing: "Infundiendo energía arcana", logoArcane: "AL arcano · suelta para recomponer",
        logoCharging: "Cargando energía · mantén pulsado", logoUnlocking: "Desbloqueando la armadura", logoOpening: "Revelando el núcleo", logoReturning: "Recomponiendo el AL",
        heroDescription: "Sitios que hacen memorable tu marca. Sistemas que simplifican tu empresa. Del primer concepto al último detalle, construyo para llevar tu negocio más lejos.",
        heroNote: "Diseño con intención. Código que resuelve.", start: "Creemos tu proyecto", viewWork: "Explora los proyectos", scroll: "Desliza para descubrir",
        selected: "Trabajo seleccionado", workTitle: "Ideas hechas realidad.", workDescription: "Negocios diferentes. Soluciones creadas para cada uno. Descubre proyectos que ya salieron del papel.",
        all: "Todos", websites: "Sitios", systems: "Sistemas", previous: "Proyecto anterior", next: "Próximo proyecto", visit: "Abrir proyecto", scrollWork: "Sigue deslizando para explorar", workCount: "proyectos seleccionados",
        solutions: "Lo que construyo", servicesTitle: "El diseño es solo el comienzo.", servicesDescription: "Tu presencia digital debe trabajar para ti. De la primera impresión a la operación diaria, cada solución tiene un propósito.",
        serviceResults: ["Tu marca, con credibilidad.", "Del interés a la conversación.", "Menos tareas. Más control.", "Mejor código. Equipo más fuerte."],
        statement: "Tu próximo sitio puede ser la mejor primera impresión de tu negocio. Tu próximo sistema, el cambio que le faltaba a tu rutina.",
        aboutLabel: "Quién construye contigo", aboutTitle: "Hola, soy Alex.", aboutIntro: "Conecto lo que tu negocio necesita con lo que la tecnología puede hacer.",
        aboutBody: "Soy desarrollador Full Stack y fundador de TKZ Dev. Trabajo de cerca con cada cliente para transformar ideas en sitios y sistemas con identidad, rendimiento y una experiencia que tiene sentido para quien los usa.",
        aboutExtra: "Hablas directamente con quien crea tu proyecto. De la estrategia al lanzamiento, cuido el diseño, el código y los detalles que hacen que funcione en el mundo real.",
        experience: "Mi trayectoria", processLabel: "De la conversación al lanzamiento", processTitle: "Un proceso claro. Un proyecto tuyo.", feedbackLabel: "Quienes ya confiaron", feedbackTitle: "Proyectos entregados. Relaciones construidas.",
        stackLabel: "Detrás de cada entrega", stackTitle: "Creatividad al frente. Tecnología en la base.", contactLabel: "El próximo proyecto puede ser tuyo", contactLines: ["Hagamos tu", "idea realidad."],
        contactDescription: "Cuéntame sobre tu negocio y lo que quieres construir. La primera conversación es el comienzo de una buena idea.", whatsapp: "Hablar por WhatsApp", email: "¿Prefieres correo?", backTop: "Volver arriba",
        navLabel: "Menú principal", openMenu: "Abrir menú", closeMenu: "Cerrar menú", pause: "Pausar animaciones", resume: "Activar animaciones", motion: "Movimiento", motionOn: "Activo", motionOff: "Pausado",
        footerNote: "Hecho con intención, del diseño al código.", clientFocus: "Sitios y sistemas a medida", portraitAlt: "Alex Lima, desarrollador Full Stack",
        projectKinds: ["Plataforma de oportunidades", "E-commerce y catálogo", "Sitio institucional", "SaaS y gestión"],
    },
}
